name: volna
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/milk_3.2.png
    - assets/images/milk_2.5.png
    - assets/images/milk_1.5.png
    - assets/images/bread_white.png
    - assets/images/bread_rye.png
    - assets/images/baguette.png
    - assets/images/apples.png
    - assets/images/bananas.png
    - assets/images/chicken.png
    - assets/images/pork.png
    - assets/logo.svg
    - assets/title.svg